### ISSUE TITLE
Wifi issues on tissot since upgrade to 7.6 

### ISSUE THREAD

**Issue by clebig** [crdroidandroid/android_device_xiaomi_tissot#1]
Hi,

I'm having wifi problems since I upgraded from 7.5 to 7.6.
While the received signal strength is good on my A1, it disconnects from any wifi network if I get few meters away from access points I use everyday at home and at work,
I can tell that this behavior didn't trigger on versions before 7.5.  
I tried wiping the data partition, same behavior. When restored a version 7.5 of crDroid, it worked again, clean flash and dirty flash.
From my Aruba and Ruckus Access points, I can see that on 7.5, the RSSI on the AP is very low compared to when I connect using 7.6. So it seems that a bug is altering the tx power somewhere in the code, and that this change is recent.

I found this in the changelog for crDroid 7.6 for tissot : `
  * frameworks/opt/net/wifi
7528058 Merge 'lineage-18.1' into 11.0`

Could it be related ?

Thanks for your incredible work.

**Comment by Sohil876** [comment]
Idk, no one else reported such issue, and unfortunately my device died so im no longer maintaining crdroid, ill close this, if someone picks it up and you still face this issue then report it to them and they'll look into it.

**Comment by clebig** [comment]
Yes, I saw that on the telegram channel. Deep condolences for it, I share you pain.
Thank you anyway for the great work you have done on this port and the time spent on it for us !
